Generate test vectors for XofHmacSha256Aes128 and Field32
Added a .mypy.ini to suppress warnings about untyped import
from sage.all:
field32.py:1: error: Skipping analyzing "sage.all": module is
installed, but missing library stubs or py.typed marker  [import-untyped]